version: "3.7"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 8880:80
      - 8881:81
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mockoon

  mockoon:
    image: mockoon/cli:latest
    container_name: mockoon
    command: ["--data", "data", "--port", "3000"]
    # if we dont need Nginx we can instead use mockoon directly
    #ports:
    #  - "8008:3000"
    volumes:
      - ./fakedata/fakedata.json:/data:readonly

